# Generated by Django 4.1.5 on 2023-03-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AddField(
            model_name="user",
            name="full_name",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
