# Generated by Django 4.1.5 on 2023-04-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_artist",
            field=models.BooleanField(default=False),
        ),
    ]
