# Generated by Django 4.1.5 on 2023-04-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_name", models.TextField(default="")),
                ("artist_endpoint", models.TextField(default="")),
                ("artist_bio", models.TextField(default="")),
            ],
            options={
                "verbose_name_plural": "Artists",
            },
        ),
    ]
