# Generated by Django 4.1.5 on 2023-04-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="spotify_id",
            field=models.TextField(default=""),
        ),
    ]
