# Generated by Django 4.1.5 on 2023-04-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artists", "0002_artist_spotify_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="followers",
            field=models.IntegerField(default=0),
        ),
    ]
